In [4]:
import numpy as np
a1=[20,40,5,70,10]
a2=[6,2,9,7,1]
a=np.array(a1)
b=np.array(a2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)



[20 40  5 70 10]
[6 2 9 7 1]
[26 42 14 77 11]
[14 38 -4 63  9]
[120  80  45 490  10]
[ 3.33333333 20.          0.55555556 10.         10.        ]


In [7]:
import numpy as np
a=np.array(a1)
b=np.array(a2)
print(a.dot(b))
sclr=3
print("scalar values",sclr)

print("array",a)

print("result",a*sclr)



745
scalar values 3
array [20 40  5 70 10]
result [ 60 120  15 210  30]


In [8]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [10]:
def my_fun(x,y):
    if x>y:
        return x-y
    else:
        return x+y
    
a1=[10,7,2]
a2=[6,5,3]
vect_fun=np.vectorize(my_fun)
print(a1)
print(a2)
print(vect_fun(a1,a2))




[10, 7, 2]
[6, 5, 3]
[4 2 5]
